apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    shared-ops-gw: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: istio
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  interval: 1h0m0s
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
    meta.helm.sh/release-name: istio-base
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-namespace: istio-system
spec:
  releaseName: istio-base
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      version: "${version}"
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 1h0m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  releaseName: istiod
  dependsOn:
  - name: istio-base
  chart:
    spec:
      version: "${version}"
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 1h0m0s
  values:
    global:
      istioNamespace: istio-system
      proxy:
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
    pilot:
      autoscaleEnabled: true
      autoscaleMin: 1
      autoscaleMax: 5
      resources:
        requests:
          cpu: 100m
          memory: 128Mi